### PR TITLE
Correct ToggleJson support for creating schemas

### LINKED ISSUE #1030: Tenant UI: JSON toggle on Create Schema is broken
No matter what I input, toggling the JSON switch throws an invalid error, nothing in console log.

image

Having similar issue in the Offer Credential feature (complaining about an invalid json). Should fix that with this.

### PR DESCRIPTION
**Pull request by Gavinok**
This PR resolves #1030

Uncertain as to why this is necessary but for whatever reason showRawJson defaulting to a false value seemed to never be properly applied and needed to be defaulted to true. For this reason it's usage has been inverted and the variable has been renamed to displayAsForm.

### CODE REVIEW

**Review by loneil — CHANGES_REQUESTED** [review]
When opening the schema screen it looks like it's toggled over to JSON to start when it's on the form mode by default

image

**Comment by Gavinok** [comment]
For some reason the input switch seems to consider it's self to always be invalid. As far as the direction of the button this seems to only update displayAsForm when it is defaulted to true. I will poke around at the internals of primevue to see if I can get an explanation to why.

**Comment by Gavinok** [comment]
I have found the culprit 

https://github.com/bcgov/traction/blob/restore-json-toggle-schema/services/tenant-ui/frontend/src/assets/primevueOverrides/inputSwitch.scss#L3-L22

@loneil From what I can tell this is taking advantage of the `.p-inputswitch-checked` class which isn't being used by the input switch at all. 

If you look at the profile settings the same issue is occurring



I modified the code to now use `[data-p-highlight="true"]` as the checked indicator. I also made some smaller changes which should make the code a lot closer to the original.

**Comment by loneil** [comment]
Ok I'd guess that `p-inputswitch-checked` class got removed at some point in a Primevue version change.

File: services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue [hunk 1]
```diff
@@ -54,6 +54,7 @@
 
 <script setup lang="ts">
 // Libraries
+import Tester from '@/components/common/./Tester.vue';
```
Comment (loneil) [inline services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue:57]: Is this a leftover?

File: services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue [hunk 2]
```diff
@@ -204,17 +206,19 @@ function jsonToSchema(jsonString: string): SchemaSendRequest | undefined {
...
 // Form submission
 const submitted = ref(false);
 const handleSubmit = async (isFormValid: boolean) => {
   submitted.value = true;
-
+  console.log('trying to validate');
   try {
+    console.log('is valid?');
     if (!isFormValid) return;
+    console.log('valid');
```
Comment (loneil) [inline services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue:221]: Probably don't need these logs

**Review by loneil — COMMENTED** [review]
Working for me on this PR, just a couple comments

File: services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue (hunk 2 above)
Comment (Gavinok) [reply services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue]: Both are just leftovers from testing the colour toggling. I have now removed them. Thanks for the review!

File: services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue [hunk 3]
```diff
@@ -74,6 +74,7 @@ import ToggleJson from '@/components/common/ToggleJson.vue';
 const toast = useToast();
 const { t } = useI18n();
 
+const other = ref(false);
```
Comment (loneil) [inline services/tenant-ui/frontend/src/components/issuance/schemas/CreateSchemaForm.vue:77]: Another one

**Review by loneil — APPROVED** [review]
